# Site settings
title: Yoohv
email: zyoohv@gmail.com
description: "Work for fun, Live for love."
url: "https://github.com/zyoohv/zyoohv.github.io/blob/master/_posts"
twitter_username: zyoohv
github_username:  zyoohv

# Build settings
markdown: kramdown
permalink: pretty
