# Site settings
title: Yoohv Zo
email: zyoohv@gmail.com
description: "Work for fun, Live for love."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: zyoohv
github_username:  zyoohv

# Build settings
markdown: kramdown
permalink: pretty
