# Site settings
title: Yoohv
email: zyoohv@gmail.com
description: "Work for fun, Live for love."
postsurl: "https://github.com/zyoohv/zyoohv.github.io/tree/master/_posts/"
baseurl: "https://zyoohv.github.io"
url: "https://zyoohv.github.io"
twitter_username: zyoohv
github_username:  zyoohv

# Build settings
markdown: kramdown
permalink: pretty
